{Message} = require.main.require 'hubot'

class PresenceMessage extends Message
  # Represents a message generated by a presence change event
  #
  # users      - Array of users that changed their status
  # presence   - Status is either 'active' or 'away'
  constructor: (@users, @presence) ->
    super @users

module.exports = PresenceMessage
