{Message} = require.main.require 'hubot'

class PresenceMessage extends Message
  # Represents a message generated by a presence change event
  #
  # user      - A User instance that reacted to the item.
  constructor: (@user) ->
    super @user

module.exports = PresenceMessage
