{Message} = require.main.require 'hubot'

class ReactionMessage extends Message
  # Represents a message generated by an emoji reaction event
  #
  # message - the original message
  constructor: (@type, @user, @reaction, @item_user, @item, @event_ts) ->
    super @user
    @type = @type.replace('reaction_', '')

module.exports = ReactionMessage
